apiVersion: apps/v1
kind: Deployment
metadata:
    name: java-api-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: api
    template:
        metadata:
            labels:
                component: api
        spec:
            containers:
                - name: api
                  image: namanv3/connection-api
                  ports:
                      - containerPort: 4567
                  env:
                      - name: MONGODB_HOST
                        value: mongodb-cluster-ip-service
                      - name: MONGODB_PORT
                        value: '27017'
